Aqui vamos rever os seguintes conceitos sobre álgebra linear

* O que são vetores?
* O que são matrizes?
* Multiplicação matriz x vetor, vetor x vetor e matriz x matriz
* Tamanho de um vetor (norm)

Material auxiliar

Essence of Linear Algebra por 3Blue1Brown no YouTube https://www.youtube.com/watch?v=kjBOesZCoqc&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=1

In [2]:
import numpy as np

## O que é um vetor?

De forma bem simplificada, é um conjunto de números com uma direção e tamanho.

É importante notar que a notação normal é definir o vetor como coluna e não como linha.

$$\mathbf{v} = \begin{bmatrix} 4 \\ 1 \\ 10 \end{bmatrix}$$

In [13]:
# um vetor no numpy
v = np.array([
    [4], 
    [1], 
    [10]
])

print(v)

[[ 4]
 [ 1]
 [10]]


Existem duas operações fundamentais com vetores: soma e multiplicação por escalar.

A soma de vetores é definida como

$$
\mathbf{x} = \begin{bmatrix} 4 \\ 1 \\ 10 \end{bmatrix}
$$

$$
\mathbf{y} = \begin{bmatrix} 5 \\ 8 \\ -1 \end{bmatrix}
$$

$$
\mathbf{x} + \mathbf{y} 
= 
\begin{bmatrix} 4 + 5 \\ 1 + 8 \\ 10 + (-1) \end{bmatrix}
= 
\begin{bmatrix} 9 \\ 9 \\ 9 \end{bmatrix}
$$

In [15]:
# com numpy
x = np.array([
    [4],
    [1],
    [10]
])

y = np.array([
    [5],
    [8],
    [-1]
])

v = x + y
print(v)

[[9]
 [9]
 [9]]


A multiplicação por escalar é definida como

$$
\mathbf{x} = \begin{bmatrix} 4 \\ 1 \\ 10 \end{bmatrix}
$$

$$
7\mathbf{x}
= 
\begin{bmatrix} 7 \cdot 4 \\ 7 \cdot 1 \\ 7 \cdot 10 \end{bmatrix}
= 
\begin{bmatrix} 28 \\ 7 \\ 7 0 \end{bmatrix}
$$

In [16]:
# com numpy
x = np.array([
    [4],
    [1],
    [10]
])

v = 7 * x
print(v)

[[28]
 [ 7]
 [70]]


Outra operação comum é a transposição, que é basicamente trocar as linhas pelas colunas.

$$
\mathbf{x} = \begin{bmatrix} a \\ b \\ c \end{bmatrix}
$$

$$
\mathbf{x}^T = \begin{bmatrix} a & b & c \end{bmatrix}
$$

In [18]:
# com numpy
x = np.array([
    [4],
    [1],
    [10]
])

print(x.T)

[[ 4  1 10]]


## O que são matrizes?

## Multiplicação matriz x vetor

A multiplicação de uma matriz por um vetor resulta em uma transformação linear do vetor.

A matriz representa a transformação e o vetor representa as coordenadas iniciais.

A multiplicação de uma matriz por um vetor tem a forma

$$
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
\begin{bmatrix} e \\ f \end{bmatrix}
=
e
\begin{bmatrix} a \\ c \end{bmatrix}
+
f
\begin{bmatrix} b \\ d \end{bmatrix}
=
\begin{bmatrix}
ae + bf \\
ce + df
\end{bmatrix}
$$

In [5]:
# em código

matriz = np.array([
    [0, 1],
    [1, 0]
])

vetor = np.array([
    [2],
    [3]
])

resultado = np.zeros(vetor.shape)
for i in range(vetor.shape[0]):
    resultado[:, 0] += vetor[i, 0] * matriz[:, i]
print(resultado)

# usando numpy
resultado = np.dot(matriz, vetor)
print(resultado)

# usando operador
resultado = matriz @ vetor
print(resultado)

[[ 3.]
 [ 2.]]
[[3]
 [2]]
[[3]
 [2]]


A matriz não precisa ser quadrada como no exemplo acima. Por exemplo:

$$
\begin{bmatrix}
a & b & c \\
d & e & f
\end{bmatrix}
\begin{bmatrix} x \\ y \\ z \end{bmatrix}
=
x
\begin{bmatrix} a \\ d \end{bmatrix}
+
y
\begin{bmatrix} b \\ e \end{bmatrix}
+
z
\begin{bmatrix} c \\ f \end{bmatrix}
=
\begin{bmatrix}
ax + by + cz \\
dx + ey + fz
\end{bmatrix}
$$

In [6]:
matriz = np.array([
    [0.25, 1.0, 5.06],
    [1.31, 0.5, 2.33]
])

vetor = np.array([
    [1],
    [7],
    [0]
])

resultado = matriz @ vetor
print(resultado)

[[ 7.25]
 [ 4.81]]


## Multiplicação vetor x vetor (produto cruzado)

A multiplicação entre vetores é o produto cruzado. O resultado é o mesmo que multiplicar
a transposição do primeiro vetor pelo segundo.

Portanto, $\mathbf{x} \times \mathbf{y} = \mathbf{x}^T \mathbf{y}$

In [7]:
# em código
x = np.array([
    [1],
    [2],
    [3]
])

y = np.array([
    [3],
    [2],
    [1]
])

resultado = np.dot(x.T, y)
print(resultado)

[[10]]


## Multiplicação matriz x matriz

Para a multiplicação matriz x matriz vamos utilizar um exemplo mais prático.

Dado uma matriz de vendas ($\mathbf{V}$) com a quantidade de cada item em cada venda.

Dado uma matriz com o custo de frete ($\mathbf{F}$) de cada unidade de cada item.

A matriz $\mathbf{V}$ tem $M$ vendas por $N$ produtos.

A matriz $\mathbf{F}$ tem $N$ produtos por $Q$ transportadoras.

Ao calcular $\mathbf{C} = \mathbf{V}\mathbf{F}$, temos uma matriz de $M$ vendas por $Q$ transportadoras.

Cada item dessa matriz representa o custo de transporte de uma determinada venda.

Por exemplo, $\mathbf{C}_{12}$ possui o custo de transporte da primeira venda pela segunda transportadora.

Dessa forma, é possível descobrir com uma operação qual seria a melhor opção de frete para venda.

In [8]:
V = np.array([
    [0, 0, 0, 1, 0],
    [0, 3, 0, 0, 2],
    [0, 2, 2, 1, 0],
    [1, 0, 0, 3, 0],
    [0, 0, 0, 1, 2],
    [3, 1, 0, 2, 0],
])

F = np.array([
    [1.00, 1.05, 1.02],
    [2.50, 2.30, 3.00],
    [0.50, 0.78, 0.43],
    [0.23, 0.15, 0.39],
    [1.57, 1.46, 1.32],
])

C = V @ F
print(C)

[[  0.23   0.15   0.39]
 [ 10.64   9.82  11.64]
 [  6.23   6.31   7.25]
 [  1.69   1.5    2.19]
 [  3.37   3.07   3.03]
 [  5.96   5.75   6.84]]


## Medindo o tamanho de vetores e matrizes

O tamanho de um vetor é medido pela *p-norm*. Quando $p=1$ temos a distância Manhattan e a distância euclidiana quando $p=2$.

A *p-norm* de um vetor $\mathbf{x}$ é calculada como 
$\lvert \mathbf{x} \rvert_p = (\sum_{i=1}^{n}\lvert \mathbf{x}_i \rvert^p)^{\frac{1}{p}}$

In [9]:
# em código
vetor = np.array([
    [1],
    [7],
    [0]
])

p = 2
norm = 0
for i in range(vetor.shape[0]):
    norm += np.abs(vetor[i, 0]) ** p
norm = norm ** (1.0 / p)
print(norm)

# com numpy
norm = np.linalg.norm(vetor, 2)
print(norm)

7.07106781187
7.07106781187


Para matrizes, existe um operador similar conhecido como *Frobenius norm*.

A *Frobenius norm* de uma matriz $\mathbf{A}$ é calculada como 
$\lvert \lvert \mathbf{A} \rvert \rvert_F = (\sum_{i=1}^{m}\sum_{j=1}^{n}\lvert \mathbf{A}_{ij} \rvert^2)^{\frac{1}{2}}$

In [10]:
# em código
matriz = np.array([
    [1, 2],
    [7, 4],
    [0, 9]
])

norm = 0
for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        norm += np.abs(matriz[i, j]) ** 2
norm = norm ** (1.0 / 2)
print(norm)

# outra opção
norm = np.sqrt(np.square(np.abs(matriz)).sum())
print(norm)

# com numpy
norm = np.linalg.norm(matriz, 'fro')
print(norm)

12.2882057274
12.2882057274
12.2882057274
